### ISSUE TITLE
TypeError: requester._get_full_time() missing 1 required positional argument: 'sel'

### ISSUE THREAD

**Issue by H00pyFr00d** [jhculb/4TCT#1]
I've been attempting to run your script, but have been getting the following error, I wonder if you have any idea what it might be

```
h00pyfr00d@marvin:~/Downloads/4TCT-main/src$ python requester.py -b vg
Traceback (most recent call last):
  File "/home/h00pyfr00d/Downloads/4TCT-main/src/requester.py", line 479, in <module>
    requester_instance = requester(
  File "/home/h00pyfr00d/Downloads/4TCT-main/src/requester.py", line 29, in __init__
    self._setup_logging(logfolderpath)
  File "/home/h00pyfr00d/Downloads/4TCT-main/src/requester.py", line 439, in _setup_logging
    self._infologpath = logfolder / ("info_log" + self._get_full_time() + ".log")
TypeError: requester._get_full_time() missing 1 required positional argument: 'sel'
```

**Comment by H00pyFr00d** [comment]
On further inspection, the issue is with a static method, with an unused input parameter "sel". Removing this parameter fixes the error

**Comment by jhculb** [comment]
Ah, thank you for the great spot and fix! Just pushed the fix now.
